# UMC POS API Gateway Service - Externalized Configuration
#
# This configuration is served by Config Server to the api-gateway-service.
# See: ADR-P-api-gateway-022, ADR-P-authentication-011, ADR-F-jwt-key-management-001

spring:
  # JWT validation configuration (ADR-P-authentication-011, ADR-F-jwt-key-management-001)
  # Uses standard Spring Security OAuth2 Resource Server auto-configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${JWT_PUBLIC_KEY:classpath:keys/jwt-public.pem}

  # Redis for token blacklist verification (session-token-mgt US-003-TASK-05)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 100ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Cloud Gateway additional configuration
  cloud:
    gateway:
      # Enable service discovery locator for automatic route generation
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Default filters applied to all routes
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback

      # Route definitions for business services
      # Routes use lb:// scheme for load-balanced routing via Eureka
      routes:
        # Auth service routes (ADR-P-authentication-011)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-cb
                fallbackUri: forward:/fallback

        # Token service routes (ADR-P-authentication-011)
        - id: token-service
          uri: lb://token-service
          predicates:
            - Path=/api/v1/tokens/**
          filters:
            - name: CircuitBreaker
              args:
                name: token-cb
                fallbackUri: forward:/fallback

        # Session management routes (session-token-mgt feature)
        - id: session-service
          uri: lb://token-service
          predicates:
            - Path=/api/v1/sessions/**
          filters:
            - name: CircuitBreaker
              args:
                name: session-cb
                fallbackUri: forward:/fallback

        # Organization service routes (org-hierarchy-mgt feature)
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/v1/hierarchy-levels/**, /api/v1/org-units/**
          filters:
            - name: CircuitBreaker
              args:
                name: organization-cb
                fallbackUri: forward:/fallback

        # User service routes (user-account-mgt feature)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-cb
                fallbackUri: forward:/fallback

        # Role service routes (role-definition feature)
        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/api/v1/roles/**, /api/v1/permissions/**
          filters:
            - name: CircuitBreaker
              args:
                name: role-cb
                fallbackUri: forward:/fallback

        # Audit service routes (ADR-P-audit-trail-026)
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - name: CircuitBreaker
              args:
                name: audit-cb
                fallbackUri: forward:/fallback

        # Article service routes
        - id: article-service
          uri: lb://article-svc
          predicates:
            - Path=/api/articles/**
          filters:
            - name: CircuitBreaker
              args:
                name: article-cb
                fallbackUri: forward:/fallback

        # Payment service routes
        - id: payment-service
          uri: lb://payment-svc
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-cb
                fallbackUri: forward:/fallback

        # Customer service routes
        - id: customer-service
          uri: lb://customer-svc
          predicates:
            - Path=/api/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer-cb
                fallbackUri: forward:/fallback

        # Transaction service routes
        - id: transaction-service
          uri: lb://transaction-svc
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: transaction-cb
                fallbackUri: forward:/fallback

      # Global CORS configuration (if needed for direct access)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# Eureka Client Configuration (ADR-P-service-discovery-021)
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
    instance-id: ${spring.application.name}:${STORE_ID:local}:${STATION_ID:${random.uuid}}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      zone: ${STORE_ID:central}
      store-id: ${STORE_ID:}
      station-id: ${STATION_ID:}
      station-type: ${STATION_TYPE:gateway}

# Actuator endpoints for health checks and metrics (ADR-P-observability-017)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,gateway
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.umc.pos.gateway: INFO
    org.springframework.cloud.gateway: INFO
    io.github.resilience4j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application info for actuator
info:
  app:
    name: UMC POS API Gateway Service
    description: API Gateway for UMC POS microservices
    version: '@project.version@'
  adr:
    reference: ADR-P-api-gateway-022

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379

eureka:
  instance:
    hostname: api-gateway-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@discovery-service:8761/eureka/

logging:
  level:
    com.umc.pos.gateway: DEBUG
