# UMC POS Role Service - Externalized Configuration
#
# This configuration is served by Config Server to the role-service.
# See: ADR-P-config-server-030, role-definition feature

# Permission Catalog (ADR-F-permission-catalog-002)
# Defines all available permissions organized by functional category.
# Permissions are system-wide and immutable at runtime.
permission-catalog:
  categories:
    role-management:
      name: Role Management
      permissions:
        - code: ROLE_CREATE
          description: Create new roles
        - code: ROLE_VIEW
          description: View role details and list
        - code: ROLE_UPDATE
          description: Modify role name and description
        - code: ROLE_DELETE
          description: Deactivate roles
        - code: ROLE_ASSIGN_PERMISSIONS
          description: Assign permissions to roles

    user-management:
      name: User Management
      permissions:
        - code: USER_CREATE
          description: Create user accounts
        - code: USER_VIEW
          description: View user details and list
        - code: USER_UPDATE
          description: Modify user information
        - code: USER_DELETE
          description: Deactivate user accounts
        - code: USER_ASSIGN_ROLES
          description: Assign roles to users
        - code: USER_RESET_PASSWORD
          description: Reset user passwords

    organization:
      name: Organization
      permissions:
        - code: ORG_VIEW
          description: View organization settings
        - code: ORG_UPDATE
          description: Modify organization settings
        - code: STORE_CREATE
          description: Create new stores
        - code: STORE_VIEW
          description: View store details
        - code: STORE_UPDATE
          description: Modify store settings
        - code: STORE_DELETE
          description: Deactivate stores

    inventory:
      name: Inventory
      permissions:
        - code: INVENTORY_VIEW
          description: View inventory levels
        - code: INVENTORY_ADJUST
          description: Adjust inventory quantities
        - code: INVENTORY_RECEIVE
          description: Receive inventory shipments
        - code: INVENTORY_TRANSFER
          description: Transfer inventory between locations
        - code: PRODUCT_CREATE
          description: Create product catalog entries
        - code: PRODUCT_VIEW
          description: View product details
        - code: PRODUCT_UPDATE
          description: Modify product information
        - code: PRODUCT_DELETE
          description: Remove products from catalog

    sales:
      name: Sales
      permissions:
        - code: SALE_CREATE
          description: Process sales transactions
        - code: SALE_VIEW
          description: View sales history
        - code: SALE_VOID
          description: Void sales transactions
        - code: SALE_REFUND
          description: Process refunds
        - code: DISCOUNT_APPLY
          description: Apply discounts to sales
        - code: PRICE_OVERRIDE
          description: Override product prices

    reporting:
      name: Reporting
      permissions:
        - code: REPORT_SALES
          description: View sales reports
        - code: REPORT_INVENTORY
          description: View inventory reports
        - code: REPORT_USER_ACTIVITY
          description: View user activity reports
        - code: REPORT_FINANCIAL
          description: View financial reports
        - code: REPORT_EXPORT
          description: Export reports to file

    audit:
      name: Audit
      permissions:
        - code: AUDIT_VIEW
          description: View audit log entries
        - code: AUDIT_EXPORT
          description: Export audit logs

# Role Conflict Configuration (US-011-TASK-01)
# Enables separation of duties enforcement via conflict rules
role-conflict:
  enabled: true
  block-by-default: false

# MongoDB Configuration (ADR-P-local-storage-007)
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/umc_pos_role}
      auto-index-creation: true

  # RabbitMQ Configuration (ADR-P-module-communication-005)
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Eureka Client Configuration (ADR-P-service-discovery-021)
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
    instance-id: ${spring.application.name}:${STORE_ID:local}:${STATION_ID:${random.uuid}}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      zone: ${STORE_ID:central}
      store-id: ${STORE_ID:}
      station-id: ${STATION_ID:}
      station-type: ${STATION_TYPE:role}

# Actuator endpoints for health checks and metrics (ADR-P-observability-017)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongo:
      enabled: true
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# OpenAPI Configuration (ADR-P-api-protocol-004)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Logging Configuration
logging:
  level:
    root: INFO
    com.umc.pos.role: INFO
    org.springframework.security: WARN
    org.springframework.data.mongodb: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application info for actuator
info:
  app:
    name: UMC POS Role Service
    description: Role management service for RBAC
    version: '@project.version@'
  feature:
    reference: role-definition

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://${MONGODB_ROOT_USERNAME:admin}:${MONGODB_ROOT_PASSWORD:admin}@mongodb:27017/umc_pos_role?authSource=admin

  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
    virtual-host: ${RABBITMQ_VHOST:umc_pos}

eureka:
  instance:
    hostname: role-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@discovery-service:8761/eureka/

logging:
  level:
    com.umc.pos.role: DEBUG
