# UMC POS Token Service - Externalized Configuration
#
# This configuration is served by Config Server to the token-service.
# See: ADR-P-authentication-011, ADR-P-config-service-020, session-token-mgt feature

# MongoDB Configuration (ADR-P-local-storage-007)
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/umc_pos}
      auto-index-creation: true

    # Redis for token blacklist (ADR-P-authentication-011)
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # RabbitMQ Configuration (ADR-P-module-communication-005)
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Token configuration (ADR-P-authentication-011)
umc:
  token:
    access-token-validity: ${TOKEN_ACCESS_VALIDITY:30m}
    refresh-token-validity: ${TOKEN_REFRESH_VALIDITY:8h}
    issuer: umc-pos
    private-key-location: ${TOKEN_PRIVATE_KEY:classpath:keys/jwt-private.pem}
    public-key-location: ${TOKEN_PUBLIC_KEY:classpath:keys/jwt-public.pem}
    key-id: ${TOKEN_KEY_ID:default-key-001}
    blacklist-ttl: ${TOKEN_BLACKLIST_TTL:35m}
    refresh-grace-period: ${TOKEN_REFRESH_GRACE:30s}

# Eureka Client Configuration (ADR-P-service-discovery-021)
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
    instance-id: ${spring.application.name}:${STORE_ID:local}:${STATION_ID:${random.uuid}}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      zone: ${STORE_ID:central}
      store-id: ${STORE_ID:}
      station-id: ${STATION_ID:}
      station-type: ${STATION_TYPE:token}

# Actuator endpoints for health checks and metrics (ADR-P-observability-017)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# OpenAPI Configuration (ADR-P-api-protocol-004)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging Configuration
logging:
  level:
    root: INFO
    com.umc.pos.token: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application info for actuator
info:
  app:
    name: UMC POS Token Service
    description: JWT token lifecycle management service
    version: '@project.version@'
  feature:
    reference: session-token-mgt

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://${MONGODB_ROOT_USERNAME:admin}:${MONGODB_ROOT_PASSWORD:admin}@mongodb:27017/umc_pos?authSource=admin

    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
    virtual-host: ${RABBITMQ_VHOST:umc_pos}

eureka:
  instance:
    hostname: token-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka}@discovery-service:8761/eureka/

logging:
  level:
    com.umc.pos.token: DEBUG
